// Generated by Wrangler on Wed Oct 16 2024 11:56:56 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DATABASE_ID: string;
  CLOUDFLARE_D1_API_TOKEN: string;
  CLOUDFLARE_D1_ACCOUNT_ID: string;
  DB: D1Database;
}
